### ISSUE TITLE
Inventory label causes error

### ISSUE THREAD

**Issue by YagiOoda** [LaunchPlatform/beancount-black#18]
It looks like the formatter doesn't like adding a label per the beancount documentation: https://beancount.github.io/docs/how_inventories_work.html

For the directive below there is an error until the label is removed.

<img width="1128" alt="Screenshot 2024-01-13 at 22 53 42" src="https://github.com/LaunchPlatform/beancount-black/assets/35860689/2f2e9337-7396-434a-9a34-3bc3f9725862">

<img width="1125" alt="Screenshot 2024-01-13 at 22 54 23" src="https://github.com/LaunchPlatform/beancount-black/assets/35860689/bfd98488-c977-4703-8cb0-a67313085548">

**Comment by fangpenlin** [comment]
Hi @YagiOoda,

Thanks for reporting the bug. I haven't looked into details yet, but just have glance, it appears to me more like a parser bug from

https://github.com/LaunchPlatform/beancount-parser

Maybe I didn't define the label syntax correctly in the parser. I will find a time to look into this.
