### ISSUE TITLE
space arounds { }

### ISSUE THREAD

**Issue by tbm** [LaunchPlatform/beancount-black#2]
bean-black made this change:

```
-  Assets:Cash                    1 FOO {10.00 EUR, 2011-12-18}
+  Assets:Cash                                                1 FOO { 10.00 EUR , 2011-12-18 }
```

Can we not have spaces around `{...}`.  IMHO `{10.00 EUR , 2011-12-18}` is better.

But maybe I just don't agree with bean-black's opiniated opinion and we have to agree to disagree.

Test case:

```
2000-01-01 open Assets:Cash
2000-01-01 open Equity:Opening-Balance

2022-01-01 * "Opening balance: cash"
  Assets:Cash                    1 FOO {10.00 EUR, 2011-12-18}
  Equity:Opening-Balance
```

**Comment by fangpenlin** [comment]
I am okay with the proposed changes as well, it's more compact and also still readable. I will make the change

**Comment by tbm** [comment]
Thanks!
