### ISSUE TITLE
Feature request: flag for exiting 1 if changes proposed

### ISSUE THREAD

**Issue by Goorzhel** [LaunchPlatform/beancount-black#23]
Similar to:
```
❯ black --help | grep -A4 -- '--check'
  --check                         Don't write the files back, just return the
                                  status. Return code 0 means nothing would
                                  change. Return code 1 means some files would
                                  be reformatted. Return code 123 means there
                                  was an internal error.
```

**Comment by fangpenlin** [comment]
Hi @Goorzhel, thanks for the suggestion. I think this feature won't be too hard to implement, but could you share the scenarios where this comes handy? Usually I would love to learn the actual scenarios before adding new features so that maybe there's a better way to do it.

**Comment by Goorzhel** [comment]
I use `bean-black` as a pre-commit hook, and when I see it's made changes I have to abort my commit, `git add` them, and try again. Having the formatter exit 1 automates the "abort commit" part.

**Comment by fangpenlin** [comment]
I see. I assume you're running beancount-black from `hooks/pre-commit` directly right? Currently we have [pre-commit](https://pre-commit.com/) hooks ready for use:

https://github.com/LaunchPlatform/beancount-black/blob/master/.pre-commit-hooks.yaml

One can write a `.pre-commit-config.yaml` with content like

```yaml
repos:
  - repo: https://github.com/LaunchPlatform/beancount-black
    rev: 1.0.0
    hooks:
      - id: beancount-black
```

then run

```bash
pre-commit install
```

to make it works. It does the file change check and aborting commit for you automatically. Would you prefer to use pre-commit instead or is there any particular reason you would rather use raw git pre-commit hook?

**Comment by Goorzhel** [comment]
I hadn't seen that, nor am I familiar with `pre-commit`-the-framework, but I'll try both and report here later.

<details><summary>And yes, I have a script in .git/hooks/pre-commit</summary>

```sh
#!/usr/bin/env -S bash -e

ag '^#!.*python' bin -l | xargs black -q --check

read -ra changed_bc_files < <(git diff --cached --name-only --diff-filter=ACM \
  | grep beancount$ | paste -sd " " )

if [ "${#changed_bc_files[@]}" -gt 0 ]; then
  bean-black -n "${changed_bc_files[@]}"
fi
```
</details>

**Comment by Goorzhel** [comment]
`pre-commit` is pretty cool! Consider me one of today's lucky [ten thousand](https://xkcd.com/1053/).

```
❯ echo -e "; uhhhhh\n\n\n\n\n\n" > uhh.beancount
❯ git add !$ && git commit -am uhhhh
alejandra............................................(no files to check)Skipped
beancount-black..........................................................Failed
- hook id: beancount-black
- files were modified by this hook

INFO:beancount_black.main:Processing file uhh.beancount
INFO:beancount_black.formatter:Calculate column width
INFO:beancount_black.formatter:Collecting
INFO:beancount_black.main:done

black................................................(no files to check)Skipped
```
