### ISSUE TITLE
format_number will use incompatible scientific notation for very small/large numbers

### ISSUE THREAD

**Issue by jonnyniv** [LaunchPlatform/beancount-black#25]
When working with commodities it can happen that you end up with small residual rounding error quantities

When bean-black formats these numbers, it will use the python Decimal representation of the number
```python
from decimal import Decimal
Decimal('0.0000001') # -> 1E-7
```
The scientific notation returned by this formatting is incompatible with beancount, and results in a syntax error (it appears that the E is interpreted as a currency).

**Comment by fangpenlin** [comment]
@jonnyniv thanks for reporting the bug. I have already fixed it 😄

**Comment by fangpenlin** [comment]
@jonnyniv I just published a new release https://github.com/LaunchPlatform/beancount-black/releases/tag/1.0.5

Can you please try again and let me know if the issue has been addressed for your use cases? 🙏

**Comment by jonnyniv** [comment]
Can confirm this fixes this up.

Thank you for the extremely fast response :smile:
