### ISSUE TITLE
Bump beancount-parser version

### ISSUE THREAD

**Issue by Soptq** [LaunchPlatform/beancount-black#8]
beancount-parser had been bumped to version 0.1.23 (https://github.com/LaunchPlatform/beancount-parser/commit/c9ec3ba02c00266d549fa830b9ca1bd4bc901b0d), resolving some parsing failures. It would be nice to bump the beancount-black version as well.

**Comment by fangpenlin** [comment]
done, now latest beancount-black supports and also requires 0.1.23 or above
